name = "hono-ecommerce"
main = "src/index.ts"
compatibility_date = "2025-02-20"
compatibility_flags = ["nodejs_compat"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true


[observability.traces]
enabled = true